### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by lutefiasco** [zeitlings/alfred-devonthink#1]
I know this is alpha, but the workflow looks very interesting. Just FYI, installing and invoking the workflow as it stands returns the following error, "“DEVONthinkPortal” can’t be opened because Apple cannot check it for malicious software." 
Alfred and DT3 both have "full disk access" in Privacy and Security, so something else is going on.

**Comment by bastianlemke** [comment]
I can confirm this problem.

**Comment by zeitlings** [comment]
Ah, hey, thanks for testing. Looks like there were some deprecated paths left in place... 

This should work: [v0.2.1-alpha](https://github.com/zeitlings/alfred-devonthink/releases/tag/v0.2.1-alpha)
Let me know if it doesn't! I don't know if updating the workflow resets the environment. If it doesn't, be sure to delete or set to 0 the "allowed" environment variable.

**Comment by lutefiasco** [comment]
That resolves the issue; it asks for permission and then runs. Installing it just added a second workflow to Alfred (I didn't try to update, merely double clicked the download), so just deleted the previous version. Cheers - looking forward to tinkering with it.
