### ISSUE TITLE
Error when triggering dvn on macOS 12

### ISSUE THREAD

**Issue by o-o-o-o-o** [zeitlings/alfred-devonthink#2]
Hi there,

I'm on macos 12.6.8, alfred 5
I'm unable to run the worklfow, I'm getting this error (from alfred debug menu):

Code 134: dyld[35221]: Symbol not found: (_$s10Foundation11FormatStylePA2A4DateV08RelativebC0VRszrlE8relative12presentation05unitsC0A2G12PresentationV_AG05UnitsC0VtFZ)
  Referenced from: '/Users/why/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.182B07C6-F7FF-47FB-B5B1-D359368A9274/src/DEVONthinkPortal'
  Expected in: '/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation'

**Comment by zeitlings** [comment]
Hey @o-o-o-o-o, that's because the deployment target was set for macOS 13.0+. I've refactored the code to accommodate macOS 12.0 in [v1.0.1](https://github.com/zeitlings/alfred-devonthink/releases/tag/v1.0.1), let me know if it works!

**Comment by o-o-o-o-o** [comment]
Thanks so much for this – it’s working.

Thanks also for taking the time to publish this plugin. I’ve made a 
hodge podge of file filter plugins, a .json related plugin that only 
deals with groups, and tried out other alfred plugins.

Looking forward to spending more time with this one.
