### ISSUE TITLE
Adding alias for: dvn |grs| 

### ISSUE THREAD

**Issue by bramadams** [zeitlings/alfred-devonthink#3]
Hi,

Thanks a lot for this Alfred workflow, it's amazing!

I mostly find myself searching for groups rather than individual files, which means I need to type "dvn [space] . [enter]" a lot anytime I want to perform a search.

It would be easier if somehow there was a way to alias "dvn |grs|" to something shorter like "dvng" or "dvg".

Is it possible to add such an alias? Or is there a convenient way for users to add these on their end? (Alfred's snippets are a possibility, but I noticed some performance issues on my Mac while typing with snippets enabled.)

Thanks!

**Comment by zeitlings** [comment]
Hey @bramadams 

The behaviour you're looking for can be achieved by using the existing external triggers.
You can just copy and paste the contents of the workflow I'm attaching here into the `DEVONthink 3 Portal` workflow, if you want to keep everything in one place or leave it as is after importing. This will add a keyword `dvg` to automatically activate the workflow and expand the relevant suffix to initiate group search: `dvn |grs| `.

The workflow: [DEVONthink 3 |grs| extension.zip](https://github.com/zeitlings/alfred-devonthink/files/14965792/DEVONthink.3.grs.extension.zip)

I am not sure if Alfred will keep the configuration of the "Call External" object, so make sure it looks like this:

<img width="679" alt="dvg_call_external" src="https://github.com/zeitlings/alfred-devonthink/assets/25689591/32b8f030-5b3e-4ee0-9b88-ef48164f730f">

**Comment by bramadams** [comment]
Hi @zeitlings ,

Thanks a lot for looking into this, the provided extension works perfectly!

(The configuration of the "Call External" object did not need any change.)

Thanks again,

BA
